[tool.poetry]
name = "hikari-utils"
version = "0.1.0"
description = "A non-exhaustive assortment of utilities for the hikari Discord API wrapper."
authors = ["Etorix <admin@etorix.dev>"]
packages = [{include = "hikariutils"}]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
hikari = "^2.1.1"
whenever = "^0.7.2"
dateparser = "^1.2.1"
regex = "^2024.11.6"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 320